### ISSUE TITLE
[Build stability] Intermittent failure in TestReceiveMetrics

### ISSUE THREAD

**Issue by nikkiattea** [sensu/sensu-go#1392]
Something in the gostatsd package is pegging memory in CI. Primarily seen in Appveyor. Attaching full stack trace of failure.
```
fatal error: out of memory

runtime stack:
runtime.throw(0xaaed38, 0xd)
	C:/go/src/runtime/panic.go:619 +0x6b
runtime.(*mcache).refill(0x24035c, 0x39144c)
	C:/go/src/runtime/mcache.go:125 +0xea
runtime.(*mcache).nextFree.func1()
	C:/go/src/runtime/malloc.go:556 +0x28
runtime.systemstack(0x0)
	C:/go/src/runtime/asm_386.s:464 +0x5e
runtime.mstart()
	C:/go/src/runtime/proc.go:1170
```
...
```
goroutine 164 [chan receive]:
github.com/sensu/sensu-go/agent.TestReceiveMetrics(0x1f7907e0)
	c:/gopath/src/github.com/sensu/sensu-go/agent/statsd_server_test.go:174 +0x216
testing.tRunner(0x1f7907e0, 0xad9bdc)
	C:/go/src/testing/testing.go:777 +0xaa
created by testing.(*T).Run
	C:/go/src/testing/testing.go:824 +0x243
```

**Comment by nikkiattea** [comment]
[log.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00d6eb9a65e90012552ede/125516c66e82c728ace21e0d46e49b9d61cec1b99de6b546a749b2ce6b137f707957a67c2687e27cba112b585a5f4fad120a5f15afeb9539e4e76224d50152a7842f4d7ed43c18a6b9871dbb06bf238e468db1bc8c5e8d.txt)

**Comment by nikkiattea** [comment]
![profile001](https://user-images.githubusercontent.com/10634078/39316312-78597376-493e-11e8-8118-08aeb84eb515.gif)

**Comment by nikkiattea** [comment]
```
(pprof) top5
Showing nodes accounting for 20.55MB, 99.55% of 20.65MB total
Dropped 47 nodes (cum <= 0.10MB)
Showing top 5 nodes out of 10
      flat  flat%   sum%        cum   cum%
   19.91MB 96.44% 96.44%    19.91MB 96.44%  github.com/sensu/sensu-go/vendor/github.com/atlassian/gostatsd/pkg/pool.NewDatagramBufferPool.func1
    0.63MB  3.05% 99.48%     0.64MB  3.11%  github.com/sensu/sensu-go/vendor/github.com/atlassian/gostatsd/pkg/statsd.NewBackendHandler
    0.01MB 0.071% 99.55%    19.94MB 96.57%  github.com/sensu/sensu-go/vendor/github.com/atlassian/gostatsd/pkg/statsd.(*DatagramReceiver).Receive
         0     0% 99.55%    19.94MB 96.59%  github.com/sensu/sensu-go/vendor/github.com/ash2k/stager/wait.(*Group).Start.func1
         0     0% 99.55%    19.94MB 96.59%  github.com/sensu/sensu-go/vendor/github.com/ash2k/stager/wait.(*Group).StartWithContext.func1
```
