### ISSUE TITLE
[Build stability] Intermittent failure in TestLeaderContention

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1401]
Failure on Appveyor:
```
[00:07:22] --- FAIL: TestLeaderContention (2.04s)
[00:07:22] panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
[00:07:22] 	panic: sync: WaitGroup is reused before previous Wait has returned
[00:07:22] 
[00:07:22] goroutine 166 [running]:
[00:07:22] testing.tRunner.func1(0x13532900)
[00:07:22] 	C:/go/src/testing/testing.go:742 +0x24a
[00:07:22] panic(0xca6ce0, 0xec3680)
[00:07:22] 	C:/go/src/runtime/panic.go:505 +0x1d0
[00:07:22] sync.(*WaitGroup).Wait(0x13587b34)
[00:07:22] 	C:/go/src/sync/waitgroup.go:131 +0xbc
[00:07:22] github.com/sensu/sensu-go/backend/leader.(*supervisor).WaitLeader(0x13587b00)
[00:07:22] 	c:/gopath/src/github.com/sensu/sensu-go/backend/leader/supervisor.go:181 +0x26
[00:07:22] github.com/sensu/sensu-go/backend/leader.TestLeaderContention(0x13532900)
[00:07:22] 	c:/gopath/src/github.com/sensu/sensu-go/backend/leader/integration_test.go:101 +0x439
[00:07:22] testing.tRunner(0x13532900, 0xe1c61c)
[00:07:22] 	C:/go/src/testing/testing.go:777 +0xaa
[00:07:22] created by testing.(*T).Run
[00:07:22] 	C:/go/src/testing/testing.go:824 +0x243
[00:07:22] FAIL	github.com/sensu/sensu-go/backend/leader	3.112s
```

**Comment by nikkiki** [comment]
Hit this recently. Prioritizing this.
```
--- FAIL: TestLeaderContention (2.29s)
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 154 [running]:
```

**Comment by echlebek** [comment]
Ugh. Let's get rid of the leader package. We don't use it anywhere and I think it's not my best work.

**Comment by nikkiki** [comment]
@echlebek as you wish 😢
