### ISSUE TITLE
Bad etcd state after invalid cluster member is added

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1928]
After creating a seemingly invalid cluster member (on an existing backend IP) using `sensuctl cluster member-add` and receiving a successful confirmation, all other cluster commands hang indefinitely including `health`, `member-list`, `member-remove`, `member-update`, and `member-add`. The backend must be forcefully terminated, and upon startup again, etcd fails to start. Etcd appears to be in an unrecoverable state. We shouldn't allow invalid user input to do this.

**Comment by nikkiki** [comment]
Steps to reproduce:
1. Start a single backend
2. `sensuctl cluster member-add new-member ip-address-of-existing-member`
3. Try to do anything else

**Comment by nikkiki** [comment]
Restarting the backend: [log.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0434b97e7f790011cceb54/125516c66e82c728ace21e0d46e49b9d61cec1b99de6b546a749b2ce6b137f707957a67c2687e27cba112b585a5f4fad120a5f15afeb9539e4e76224d50152a7842f4d7ed43c18a6b9871cbc04bd248f4784b3b5885e8d.txt)

**Comment by nikkiki** [comment]
According to [sensu-go](https://github.com/sensu/sensu-go/blob/a3fdce9c53ab1198954c921d99d0b6853332a1f4/backend/etcd/etcd.go#L123) and [etcd](https://github.com/coreos/etcd/blob/v3.3.2/embed/config.go#L245), it appears that [strict reconfiguration check mode](https://coreos.com/etcd/docs/latest/op-guide/runtime-configuration.html) is enabled.

I've reset the etcd state and reproduced for new logs. See the panic below when `sensuctl member health` is invoked.
```
{"component":"etcd","level":"info","msg":"http: panic serving 127.0.0.1:62659: runtime error: invalid memory address or nil pointer dereference\ngoroutine 630 [running]:\nnet/http.(*conn).serve.func1(0xc4206e2140)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1726 +0xd0\npanic(0x1d82400, 0x2943790)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229\ngithub.com/sensu/sensu-go/backend/store/etcd.(*Store).GetClusterHealth(0xc4208d1760, 0x2226220, 0xc42003e0e0, 0x100b60c, 0x1e3d520, 0xc420b12420)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/backend/store/etcd/health_store.go:40 +0x1c2\ngithub.com/sensu/sensu-go/backend/apid/routers.(*StatusRouter).health(0xc4208a7760, 0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/backend/apid/routers/status.go:43 +0x61\ngithub.com/sensu/sensu-go/backend/apid/routers.(*StatusRouter).(github.com/sensu/sensu-go/backend/apid/routers.health)-fm(0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/backend/apid/routers/status.go:35 +0x48\nnet/http.HandlerFunc.ServeHTTP(0xc42015d2d0, 0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44\ngithub.com/sensu/sensu-go/backend/apid/middlewares.Edition.Then.func1(0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/backend/apid/middlewares/edition.go:18 +0xc2\nnet/http.HandlerFunc.ServeHTTP(0xc4206af8c0, 0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44\ngithub.com/sensu/sensu-go/backend/apid/middlewares.LimitRequest.Then.func1(0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/backend/apid/middlewares/limitrequest.go:26 +0x1c9\nnet/http.HandlerFunc.ServeHTTP(0xc4208d1000, 0x2f4b910, 0xc4206afad0, 0xc420a4f900)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44\ngithub.com/sensu/sensu-go/backend/apid/middlewares.SimpleLogger.Then.func1(0x2224920, 0xc420a9a7e0, 0xc420a4f900)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/backend/apid/middlewares/logging.go:25 +0xfa\nnet/http.HandlerFunc.ServeHTTP(0xc4208d1140, 0x2224920, 0xc420a9a7e0, 0xc420a4f900)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44\ngithub.com/sensu/sensu-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420039a40, 0x2224920, 0xc420a9a7e0, 0xc420a4f900)\n\t/Users/nattea/go/src/github.com/sensu/sensu-go/vendor/github.com/gorilla/mux/mux.go:133 +0xed\nnet/http.serverHandler.ServeHTTP(0xc4206cb450, 0x2224920, 0xc420a9a7e0, 0xc420a4f700)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2694 +0xbc\nnet/http.(*conn).serve(0xc4206e2140, 0x22261e0, 0xc4209045c0)\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2795 +0x27b\n","pkg":"","time":"2018-08-06T14:04:59-07:00"}
```

**Comment by nikkiki** [comment]
After some investigation and reproducing the issue under several different configurations, I've determined there is not much we can do for this particular use case. It is not a recommended use case (due to the failure tolerance of even sized clusters), and member validation - if possible - seems out of scope. Attempting to manually scale from a cluster size of 1 to 2 with an invalid cluster member causes the cluster to lose quorum. Etcd cannot resume until quorum is established. Seemingly, this behavior is correct.
