### ISSUE TITLE
Panic when logging events

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2407]
Critical bug. Master branch recently broken, backends can crash with a panic.

## Expected Behavior
Backend works without panicking

## Current Behavior
```
backend2_1_88a4e3d10d82 | panic: runtime error: invalid memory address or nil pointer dereference
backend2_1_88a4e3d10d82 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x115c559]
backend2_1_88a4e3d10d82 | 
backend2_1_88a4e3d10d82 | goroutine 347 [running]:
backend2_1_88a4e3d10d82 | github.com/sensu/sensu-go/util/logging.EventFields(0xc002654800, 0xc00003e001, 0x128db40)
backend2_1_88a4e3d10d82 | 	/home/eric/go/src/github.com/sensu/sensu-go/util/logging/logging.go:31 +0x429
backend2_1_88a4e3d10d82 | github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).handleEvent(0xc000951200, 0xc002654800, 0x2, 0x1)
backend2_1_88a4e3d10d82 | 	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/handle.go:40 +0xe4
backend2_1_88a4e3d10d82 | github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000951200, 0xc00063baa0)
backend2_1_88a4e3d10d82 | 	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:136 +0x134
backend2_1_88a4e3d10d82 | created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
backend2_1_88a4e3d10d82 | 	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70
```

## Steps to Reproduce (for bugs)
Run the docker-compose and issue repeated requests to `sensuctl event list` until the crash occurs.

## Context
Discovered while doing unrelated work.

**Comment by echlebek** [comment]
Looks like this change is the culprit. Needs a nil check for event.Check.

https://github.com/sensu/sensu-go/commit/948dd2e6dfe3f21209236942dbd534a2238c328a#diff-f8d862cbff9af6c9a7584c59954864aaR31
