### ISSUE TITLE
no-embed-etcd doesn't work on stable release

### ISSUE THREAD

**Issue by Surian** [sensu/sensu-go#2499]
## Expected Behavior
We should be able to use external etcd cluster by using no-embed-etcd: true in backend configuration.

## Current Behavior
When starting sensu-backend with no-embed-etcd: true, the backend crash on start with this error:

<details>
 <summary>Sensu Go Backend Panic</summary>

```
Dec 07 09:55:27 ip-10-107-110-113 systemd[1]: Started The Sensu Backend service..
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: {"component":"ee-backend","level":"error","msg":"dial tcp 127.0.0.1:2379: connect: connection refused","time":"2018-12-07T09:55:32+01:00"}
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11bd68e]
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: goroutine 1 [running]:
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: github.com/sensu/sensu-enterprise-go/backend.Initialize(0xc4201cac80, 0x1a, 0x0, 0x0)
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/backend/backend.go:26 +0xae
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc4200dbb80, 0xc4201c5040, 0x0, 0x2, 0x0, 0x0)
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:214 +0xf51
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200dbb80, 0xc4201c5020, 0x2, 0x2, 0xc4200dbb80, 0xc4201c5020)
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2218ba0, 0xc420081980, 0xc420080060, 0xc420080060)
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x2218ba0, 0x403e4c, 0xc42008a058)
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1844e78, 0x0, 0x0)
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]: main.main()
Dec 07 09:55:32 ip-10-107-110-113 sensu-backend[3512]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
Dec 07 09:55:32 ip-10-107-110-113 systemd[1]: sensu-backend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 ```
</details>

## Steps to Reproduce (for bugs)
1. Install sensu-backend
2. Set no-embed-etcd: true and etcd-listen-client-urls to an external etcd cluster
3. Start sensu-backend

## Context
sensu-backend configuration file:

state-dir: "/var/lib/sensu"
etcd-listen-client-urls: "http://sensu-etcd-cluster.[hidden].com:2379"
no-embed-etcd: true
log-level: "debug"

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.0.0
* Installation method (packages, binaries, docker etc.): debian package
* Operating System and version (e.g. Ubuntu 14.04): ubuntu 18.04

**Comment by Surian** [comment]
Found the cause, no-embed-etcd must be now associated with etcd-advertise-client-urls. The documentation is not up to date and the changelog just tell "added etcd-advertiste-client-urls".

But, even with this problem solved. there is still an issue. Here is the error after changing etcd-listen-client-urls to etcd-advertise-client-urls and starting the backend:

Dec 07 11:45:21 tech-sensu-backend-staging-110085 systemd[1]: Started The Sensu Backend service..
Dec 07 11:45:21 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"component":"backend","level":"debug","msg":"Initializing store...","time":"2018-12-07T11:45:21+01:00"}
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"component":"backend","level":"debug","msg":"Done initializing store","time":"2018-12-07T11:45:22+01:00"}
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"component":"backend","level":"debug","msg":"Registering backend...","time":"2018-12-07T11:45:22+01:00"}
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"component":"backend","level":"debug","msg":"Done registering backend.","time":"2018-12-07T11:45:22+01:00"}
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"component":"backend","entity":{"entity_class":"backend","system":{"hostname":"tech-sensu-backend-staging-110085","os":"linux","platform":"ubuntu","platform_family":"d
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"cache":"/var/cache/sensu/sensu-backend","component":"asset-manager","level":"debug","msg":"initializing cache directory","time":"2018-12-07T11:45:22+01:00"}
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: {"cache":"/var/cache/sensu/sensu-backend","component":"asset-manager","level":"debug","msg":"done initializing cache directory","time":"2018-12-07T11:45:22+01:00"}
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe9c318]
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: goroutine 1 [running]:
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/etcd.(*Etcd).NewClient(0x0, 0xc4200928c0, 0x0, 0x0)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/etcd/etcd.go:207 +0x68
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/backend.Initialize(0xc420250500, 0x1a, 0x0, 0x0)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/backend/backend.go:26 +0xbb
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc4200cbb80, 0xc4201b9000, 0x0, 0x2, 0x0, 0x0)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:214 +0xf51
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200cbb80, 0xc4201b8fe0, 0x2, 0x2, 0xc4200cbb80, 0xc4201b8fe0)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2218ba0, 0xc420081740, 0xc4201fc840, 0xc4201fc840)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x2218ba0, 0x403e4c, 0xc42008a058)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1844e78, 0x0, 0x0)
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]: main.main()
Dec 07 11:45:22 tech-sensu-backend-staging-110085 sensu-backend[2115]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
Dec 07 11:45:22 tech-sensu-backend-staging-110085 systemd[1]: sensu-backend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by Surian** [comment]
Dec 07 13:44:53 ip-10-107-122-171 systemd[1]: Started The Sensu Backend service..
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: {"component":"ee-backend","level":"error","msg":"context deadline exceeded","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11bd68e]
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: goroutine 1 [running]:
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: github.com/sensu/sensu-enterprise-go/backend.Initialize(0xc4201bec80, 0x1a, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/backend/backend.go:26 +0xae
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc4200cbb80, 0xc4201b9060, 0x0, 0x2, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:214 +0xf51
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200cbb80, 0xc4201b9040, 0x2, 0x2, 0xc4200cbb80, 0xc4201b9040)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2218ba0, 0xc420081800, 0xc420080060, 0xc420080060)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x2218ba0, 0x403e4c, 0xc42008a058)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1844e78, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]: main.main()
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13220]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: sensu-backend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: sensu-backend.service: Failed with result 'exit-code'.
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: sensu-backend.service: Service hold-off time over, scheduling restart.
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: sensu-backend.service: Scheduled restart job, restart counter is at 1.
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: Stopped The Sensu Backend service..
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: Started The Sensu Backend service..
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"component":"backend","level":"debug","msg":"Initializing store...","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"component":"backend","level":"debug","msg":"Done initializing store","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"component":"backend","level":"debug","msg":"Registering backend...","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"component":"backend","level":"debug","msg":"Done registering backend.","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"component":"backend","entity":{"entity_class":"backend","system":{"hostname":"ip-10-107-122-171","os":"linux","platform":"ubuntu","platform_family":"debian","platform_version":"18.04","network":{"interfaces":[{"name":"lo","addresses":["127.0.0.1/8","::1/128"]},{"name":"ens5","mac":"06:29:86:81:1e:1e","addresses":["10.107.122.171/24","fe80::429:86ff:fe81:1e1e/64"]}]},"arch":"amd64"},"subscriptions":null,"last_seen":0,"deregister":false,"deregistration":{},"metadata":{"name":"ip-10-107-122-171"}},"level":"info","msg":"backend entity information","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"cache":"/var/cache/sensu/sensu-backend","component":"asset-manager","level":"debug","msg":"initializing cache directory","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: {"cache":"/var/cache/sensu/sensu-backend","component":"asset-manager","level":"debug","msg":"done initializing cache directory","time":"2018-12-07T13:44:58Z"}
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe9c318]
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: goroutine 1 [running]:
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/etcd.(*Etcd).NewClient(0x0, 0xc420220690, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/etcd/etcd.go:207 +0x68
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/backend.Initialize(0xc42024d400, 0x1a, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/backend/backend.go:26 +0xbb
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc42024cc80, 0xc4202e2800, 0x0, 0x2, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:214 +0xf51
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc42024cc80, 0xc4202e27e0, 0x2, 0x2, 0xc42024cc80, 0xc4202e27e0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2218ba0, 0xc4202b72c0, 0xc4202b60c0, 0xc4202b60c0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x2218ba0, 0x403e4c, 0xc42008a058)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1844e78, 0x0, 0x0)
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]: main.main()
Dec 07 13:44:58 ip-10-107-122-171 sensu-backend[13254]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: sensu-backend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 13:44:58 ip-10-107-122-171 systemd[1]: sensu-backend.service: Failed with result 'exit-code'.
Dec 07 13:44:59 ip-10-107-122-171 systemd[1]: sensu-backend.service: Service hold-off time over, scheduling restart.
Dec 07 13:44:59 ip-10-107-122-171 systemd[1]: sensu-backend.service: Scheduled restart job, restart counter is at 2.
Dec 07 13:44:59 ip-10-107-122-171 systemd[1]: Stopped The Sensu Backend service..
Dec 07 13:44:59 ip-10-107-122-171 systemd[1]: Started The Sensu Backend service..
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: {"component":"ee-backend","level":"error","msg":"context deadline exceeded","time":"2018-12-07T13:45:04Z"}
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11bd68e]
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: goroutine 1 [running]:
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: github.com/sensu/sensu-enterprise-go/backend.Initialize(0xc4201bcc80, 0x1a, 0x0, 0x0)
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/backend/backend.go:26 +0xae
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc4200cbb80, 0xc4201b7060, 0x0, 0x2, 0x0, 0x0)
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:214 +0xf51
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200cbb80, 0xc4201b7040, 0x2, 0x2, 0xc4200cbb80, 0xc4201b7040)
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2218ba0, 0xc420081740, 0xc4202088a0, 0xc4202088a0)
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x2218ba0, 0x403e4c, 0xc42008a058)
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1844e78, 0x0, 0x0)
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]: main.main()
Dec 07 13:45:04 ip-10-107-122-171 sensu-backend[13294]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
Dec 07 13:45:04 ip-10-107-122-171 systemd[1]: sensu-backend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 13:45:04 ip-10-107-122-171 systemd[1]: sensu-backend.service: Failed with result 'exit-code'.
Dec 07 13:45:04 ip-10-107-122-171 systemd[1]: sensu-backend.service: Service hold-off time over, scheduling restart.
Dec 07 13:45:04 ip-10-107-122-171 systemd[1]: sensu-backend.service: Scheduled restart job, restart counter is at 3.
Dec 07 13:45:04 ip-10-107-122-171 systemd[1]: Stopped The Sensu Backend service..
Dec 07 13:45:04 ip-10-107-122-171 systemd[1]: Started The Sensu Backend service..
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: {"component":"ee-backend","level":"error","msg":"context deadline exceeded","time":"2018-12-07T13:45:09Z"}
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11bd68e]
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: goroutine 1 [running]:
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: github.com/sensu/sensu-enterprise-go/backend.Initialize(0xc42023b400, 0x1a, 0x0, 0x0)
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/backend/backend.go:26 +0xae
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc42023ac80, 0xc420240860, 0x0, 0x2, 0x0, 0x0)
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:214 +0xf51
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc42023ac80, 0xc420240840, 0x2, 0x2, 0xc42023ac80, 0xc420240840)
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2218ba0, 0xc420204c60, 0xc420204fc0, 0xc420204fc0)
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x2218ba0, 0x403e4c, 0xc42008a058)
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1844e78, 0x0, 0x0)
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]: main.main()
Dec 07 13:45:09 ip-10-107-122-171 sensu-backend[13328]:         /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
Dec 07 13:45:09 ip-10-107-122-171 systemd[1]: sensu-backend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 13:45:09 ip-10-107-122-171 systemd[1]: sensu-backend.service: Failed with result 'exit-code'.
Dec 07 13:45:09 ip-10-107-122-171 systemd[1]: sensu-backend.service: Service hold-off time over, scheduling restart.
Dec 07 13:45:09 ip-10-107-122-171 systemd[1]: sensu-backend.service: Scheduled restart job, restart counter is at 4.
Dec 07 13:45:09 ip-10-107-122-171 systemd[1]: Stopped The Sensu Backend service..
