### ISSUE TITLE
segmentation violation when stopping sensu-backend

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2586]
## Expected Behavior

sensu-backend should exit cleanly when service is stopped

## Current Behavior

sensu-backend may exit uncleanly when stopped

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Stopping the sensu-backend service results in a segmentation violation (SIGSEGV):

```
{"component":"etcd","level":"warning","msg":"simple token is not cryptographically signed","pkg":"auth","time":"2018-12-27T07:20:12-05:00"}

{"component":"etcd","level":"warning","msg":"set the initial cluster version to 3.3","pkg":"etcdserver/membership","time":"2018-12-27T07:20:12-05:00"}

{"component":"ee-licensing","level":"error","msg":"No enterprise license found","time":"2018-12-27T07:20:13-05:00"}

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8cd921]

 

goroutine 1 [running]:

net/http.(*Server).Shutdown(0xc4202bb380, 0x0, 0x0, 0x0, 0x0)

        /usr/local/go/src/net/http/server.go:2581 +0x1a1

github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/dashboardd.(*Dashboardd).Stop(0xc4200232c0, 0xc4207d56f8, 0x2)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/dashboardd/dashboardd.go:101 +0x3b

github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend.stopGroup.Stop(0xc420183800, 0x8, 0x8, 0x1, 0x9)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/backend.go:330 +0x12e

github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend.(*Backend).Run(0xc42007cd80, 0x0, 0x0)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/backend.go:288 +0x7e1

github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.newStartCommand.func1(0xc4201ba280, 0xc42000a720, 0x0, 0x2, 0x0, 0x0)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/start.go:234 +0x106c

github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201ba280, 0xc42000a5e0, 0x2, 0x2, 0xc4201ba280, 0xc42000a5e0)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x468

github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x221abc0, 0xc42007c5a0, 0xc42007c060, 0xc42007c060)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x30a

github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0x221abc0, 0x403e4c, 0xc420086058)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b

github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd.Execute(0x1846680, 0x0, 0x0)

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/backend/cmd/root.go:23 +0x43

main.main()

        /home/circleci/sensu-obj/go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-backend/main.go:14 +0x2d
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend version 5.1.0#b2ea9fc, build b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, built '2018-12-18T21:31:11+0000'
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by echlebek** [comment]
The dashboard's HTTP server is passed a nil context when Shutdown is called. This is the source of the panic; the stdlib server tries to return the result of the context's Err() method.
