### ISSUE TITLE
Error deleting secrets API provider

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3521]
## Expected Behavior

I'd expect invalid delete request to not result in null pointer exception.

## Current Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdd407b]

goroutine 1 [running]:
github.com/sensu/sensu-enterprise-go/api/secrets/v1.(*VaultProvider).UnmarshalJSON(0xc0003308f0, 0xc0000ef400, 0x18, 0x200, 0x7fea140e7218, 0xc0003308f0)
        /go/src/github.com/sensu/sensu-enterprise-go/api/secrets/v1/vault_provider.go:217 +0xeb
encoding/json.(*decodeState).object(0xc0002e8448, 0xf7e300, 0xc0002c5f20, 0x16, 0xc0002e8470, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:667 +0x220b
encoding/json.(*decodeState).value(0xc0002e8448, 0xf7e300, 0xc0002c5f20, 0x16, 0xc000247458, 0x6710de)
        /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).unmarshal(0xc0002e8448, 0xf7e300, 0xc0002c5f20, 0x0, 0x1)
        /usr/local/go/src/encoding/json/decode.go:179 +0x1fb
encoding/json.(*Decoder).Decode(0xc0002e8420, 0xf7e300, 0xc0002c5f20, 0xd, 0x7fea140e71c8)
        /usr/local/go/src/encoding/json/stream.go:73 +0x166
github.com/sensu/sensu-go/types.(*Wrapper).UnmarshalJSON(0xc0003254a0, 0xc0000ef200, 0x8c, 0x200, 0x7fea140e7108, 0xc0003254a0)
        /go/pkg/mod/github.com/sensu/sensu-go@v0.0.0-20200124201345-db7dc8834c4e/types/wrapper.go:136 +0x39f
encoding/json.(*decodeState).object(0xc0002e82e8, 0x112cec0, 0xc0003254a0, 0x16, 0xc0002e8310, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:667 +0x220b
encoding/json.(*decodeState).value(0xc0002e82e8, 0x112cec0, 0xc0003254a0, 0x16, 0xc000247aa8, 0x6710de)
        /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).unmarshal(0xc0002e82e8, 0x112cec0, 0xc0003254a0, 0x0, 0x1)
        /usr/local/go/src/encoding/json/decode.go:179 +0x1fb
encoding/json.(*Decoder).Decode(0xc0002e82c0, 0x112cec0, 0xc0003254a0, 0x0, 0x8c)
        /usr/local/go/src/encoding/json/stream.go:73 +0x166
github.com/sensu/sensu-go/cli/commands/create.ParseResources(0x1335b80, 0xc00000f1f0, 0x1335b80, 0xc00000f1f0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/sensu/sensu-go@v0.0.0-20200124201345-db7dc8834c4e/cli/commands/create/create.go:201 +0x1e7
github.com/sensu/sensu-go/cli/commands/delete.execute.func1(0xc000323680, 0xc00030c680, 0x0, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/sensu/sensu-go@v0.0.0-20200124201345-db7dc8834c4e/cli/commands/delete/delete.go:46 +0xc0
github.com/spf13/cobra.(*Command).execute(0xc000323680, 0xc00030c620, 0x2, 0x2, 0xc000323680, 0xc00030c620)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002b8c80, 0xc0001ad590, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /go/src/github.com/sensu/sensu-enterprise-go/cmd/sensuctl/main.go:36 +0xcc
```

## Steps to Reproduce (for bugs)

Generate JSON with `null` for `client`.
```
[root@sensu_backend /]# cat vaultprovider.json 
{
  "type": "VaultProvider",
  "api_version": "secrets/v1",
  "metadata": {
    "name": "my_vault"
  },
  "spec": {
    "client": null
  }
}
```

Try and delete secrets provider

```
[root@sensu_backend /]# sensuctl delete -f vaultprovider.json 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdd407b]

goroutine 1 [running]:
github.com/sensu/sensu-enterprise-go/api/secrets/v1.(*VaultProvider).UnmarshalJSON(0xc00030a1a0, 0xc0002fe400, 0x18, 0x200, 0x7f29b9729158, 0xc00030a1a0)
        /go/src/github.com/sensu/sensu-enterprise-go/api/secrets/v1/vault_provider.go:217 +0xeb
encoding/json.(*decodeState).object(0xc000298868, 0xf7e300, 0xc0002f0570, 0x16, 0xc000298890, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:667 +0x220b
encoding/json.(*decodeState).value(0xc000298868, 0xf7e300, 0xc0002f0570, 0x16, 0xc000213458, 0x6710de)
        /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).unmarshal(0xc000298868, 0xf7e300, 0xc0002f0570, 0x0, 0x1)
        /usr/local/go/src/encoding/json/decode.go:179 +0x1fb
encoding/json.(*Decoder).Decode(0xc000298840, 0xf7e300, 0xc0002f0570, 0xd, 0x7f29b9729108)
        /usr/local/go/src/encoding/json/stream.go:73 +0x166
github.com/sensu/sensu-go/types.(*Wrapper).UnmarshalJSON(0xc0002f81e0, 0xc0002fe200, 0x8c, 0x200, 0x7f29b9729048, 0xc0002f81e0)
        /go/pkg/mod/github.com/sensu/sensu-go@v0.0.0-20200124201345-db7dc8834c4e/types/wrapper.go:136 +0x39f
encoding/json.(*decodeState).object(0xc000298708, 0x112cec0, 0xc0002f81e0, 0x16, 0xc000298730, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:667 +0x220b
encoding/json.(*decodeState).value(0xc000298708, 0x112cec0, 0xc0002f81e0, 0x16, 0xc000213aa8, 0x6710de)
        /usr/local/go/src/encoding/json/decode.go:429 +0x6d
encoding/json.(*decodeState).unmarshal(0xc000298708, 0x112cec0, 0xc0002f81e0, 0x0, 0x1)
        /usr/local/go/src/encoding/json/decode.go:179 +0x1fb
encoding/json.(*Decoder).Decode(0xc0002986e0, 0x112cec0, 0xc0002f81e0, 0x0, 0x8d)
        /usr/local/go/src/encoding/json/stream.go:73 +0x166
github.com/sensu/sensu-go/cli/commands/create.ParseResources(0x1335b80, 0xc00000e498, 0x1335b80, 0xc00000e498, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/sensu/sensu-go@v0.0.0-20200124201345-db7dc8834c4e/cli/commands/create/create.go:201 +0x1e7
github.com/sensu/sensu-go/cli/commands/delete.execute.func1(0xc0002f2280, 0xc00000dbe0, 0x0, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/sensu/sensu-go@v0.0.0-20200124201345-db7dc8834c4e/cli/commands/delete/delete.go:46 +0xc0
github.com/spf13/cobra.(*Command).execute(0xc0002f2280, 0xc00000db80, 0x2, 0x2, 0xc0002f2280, 0xc00000db80)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000275680, 0xc000248e40, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /go/src/github.com/sensu/sensu-enterprise-go/cmd/sensuctl/main.go:36 +0xcc
```

## Context

I am prototyping secrets provider management for Puppet and ended up generating these errors.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): CI build:
`sensu-backend version 5.17.0, build a22a93be9c6a78064be51179907e6694f459a66d, built 2020-01-24T20:40:29Z`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by echlebek** [comment]
Thanks, I've moved this issue to the enterprise repo, we'll make sure it gets taken care of before release.
