### ISSUE TITLE
sensuctl enity list  "runtime error: index out of range [35] with length 35"

### ISSUE THREAD

**Issue by anatolijd** [sensu/sensu-go#4102]
## Expected Behavior
`sensuctl enity list` should return entity list. 

## Current Behavior
As admin user, I can list entities in default namespace (which is empty). There are 2 more non-default namespaces confugred - "main" and "test". 
I can list entities in "main" namspace without a problem.
I'n not able to list entities in "test" namespace - I'm getting EOF error immediately (see below).

```
# sensuctl enity list --namespace test

Error: Get https://sensu-api.acme.com:8080/api/core/v2/namespaces/test/entities: EOF
```

I can list other objects (user,handler,asset,check,event) in "test" namespace fine,   but not entity.

I can list entity in any other namespace expect "test".

sensu-backend.log for `sensuctl entity list --namespace test`
```
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","error":"EOF","level":"error","msg":"websocket connection error","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","level":"warning","msg":"http: TLS handshake error from 172.20.3.191:18606: EOF","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"etcd","level":"info","msg":"http: TLS handshake error from 172.20.99.107:37376: EOF\n","pkg":"","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"rbac","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2020-11-24T15:58:04Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"test","resource":"entities","resourceName":"","username":"admin","verb":"list"}}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"etcd","level":"info","msg":"http: panic serving 172.20.35.188:43590: runtime error: index out of range [35] with length 35\ngoroutine 534625 [running]:\nnet/http.(*conn).serve.func1(0xc005de5c20)\n
\t/usr/local/go/src/net/http/server.go:1767 +0x139\n
panic(0x16779c0, 0xc007719940)\n
\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\n
github.com/sensu/sensu-go/backend/store/etcd.entitiesFromConfigAndState(0xc000bd0000, 0x23, 0x23, 0xc000be6000, 0x24, 0x24, 0x0, 0x1a12d20, 0xc00a6209f0, 0xc00096ea38, ...)\n
\t/usr/local/src/sensu-go/backend/store/etcd/entity_store.go:240 +0x772\n
github.com/sensu/sensu-go/backend/store/etcd.(*Store).GetEntities(0xc006a661e0, 0x1a12d20, 0xc00a6209f0, 0xc00a620a20, 0xc00096ebd0, 0x5f3868, 0xc00a620150, 0x14a3ca0, 0x19b55e8)\n\t
/usr/local/src/sensu-go/backend/store/etcd/entity_store.go:233 +0x7da\n
github.com/sensu/sensu-go/backend/apid/actions.EntityController.List(0x1a18020, 0xc006a661e0, 0x1a285a0, 0xc00f9559b8, 0x1a12d20, 0xc00a6209f0, 0xc00a620a20, 0x150c4a0, 0xc00a620060, 0xc00096ec78, ...)\n\t
/usr/local/src/sensu-go/backend/apid/actions/entities.go:45 +0x62\
ngithub.com/sensu/sensu-go/backend/apid/routers.List.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab600)\n\t
/usr/local/src/sensu-go/backend/apid/routers/lister.go:45 +0x229\n
net/http.HandlerFunc.ServeHTTP(...)\n\t
/usr/local/go/src/net/http/server.go:2007\n
github.com/sensu/sensu-go/backend/apid/routers.listerHandler.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab600)\n\t
/usr/local/src/sensu-go/backend/apid/routers/lister.go:65 +0x61\n
net/http.HandlerFunc.ServeHTTP(0xc006d37fe0, 0x7fef03350200, 0xc00a6202a0, 0xc000aab600)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Pagination.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/pagination.go:34 +0x2b7\nnet/http.HandlerFunc.ServeHTTP(0xc006fefca0, 0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.LimitRequest.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t
/usr/local/src/sensu-go/backend/apid/middlewares/limitrequest.go:28 +0x221\n
net/http.HandlerFunc.ServeHTTP(0xc006fefcc0, 0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Authorization.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab000)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/authorization.go:58 +0x738\nnet/http.HandlerFunc.ServeHTTP(0xc00a620090, 0x7fef03350200, 0xc00a6202a0, 0xc000aab000)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.AuthorizationAttributes.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aaaf00)\n\t
/usr/local/src/sensu-go/backend/apid/middlewares/authorization_attributes.go:102 +0x5c4\nnet/http.HandlerFunc.ServeHTTP(0xc006fefce0, 0x7fef03350200, 0xc00a6202a0, 0xc000aaaf00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.SimpleLogger.Then.func1(0x1a0b5a0, 0xc000b13180, 0xc000aaaf00)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/logging.go:26 +0x205\nnet/http.HandlerFunc.ServeHTTP(0xc006fefd00, 0x1a0b5a0, 0xc000b13180, 0xc000aaaf00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Authentication.Then.func1(0x1a0b5a0, 0xc000b13180, 0xc000aaae00)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/authentication.go:43 +0x72a\nnet/http.HandlerFunc.ServeHTTP(0xc00a6200c0, 0x1a0b5a0, 0xc000b13180, 0xc000aaae00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Namespace.Then.func1(0x1a0b5a0, 0xc000b13180, 0xc000aaad00)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/namespace.go:29 +0x1b4\n
net/http.HandlerFunc.ServeHTTP(0xc006fefd40, 0x1a0b5a0, 0xc000b13180, 0xc000aaad00)\n\t
/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000
Nov 24 15:58:04 is-1840b sensu-backend[6750]: d18900, 0x1a0b5a0, 0xc000b13180, 0xc000aaaa00)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\n
net/http.serverHandler.ServeHTTP(0xc005d8b5e0, 0x1a0b5a0, 0xc000b13180, 0xc000aaaa00)\n\t
/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc005de5c20, 0x1a12c60, 0xc00a6b6100)\n\t
/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t
/usr/local/go/src/net/http/server.go:2927 +0x38e\n","pkg":"","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"etcd","level":"info","msg":"http: TLS handshake error from 172.20.3.191:47915: EOF\n","pkg":"","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","error":"EOF","level":"error","msg":"websocket connection error","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","level":"warning","msg":"http: TLS handshake error from 172.20.35.123:62531: EOF","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","error":"EOF","level":"error","msg":"websocket connection error","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","level":"warning","msg":"http: TLS handshake error from 172.20.35.123:43592: EOF","time":"2020-11-24T15:58:04Z"}
```

In 'test' namespace  I have over 50 agents registered, around 20 checks executed every 60 seconds, and over 1000 events.

Please help to resolve this. 

## Your Environment

* Sensu community version 6.1.3
  sensu/web revision (1.0.3): `c0890b2`
* Installation method : binary compiled from git sources.

This is reproducible via Web UI: https://github.com/sensu/web/issues/344

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/panic-serving-172-20-35-188-runtime-error-index-out-of-range-35-with-length-35/2282/1

**Comment by anatolijd** [comment]
I confirm the error has gone after I recompiled sensu-backend from master. 
I can get the list of entities now.
Thanks!
:+1:

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/4103
