### ISSUE TITLE
Sensu Backend HA cluster is Unstable

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4160]
I have a 3 node cluster in docker.

The whole cluster goes down frequently with limited error info.

   "error":"internal error: etcdserver: request timed out"

**Comment by calebhailey** [comment]
Hi there @raihanchdy 👋 these errors seem to indicate that there is an issue with etcd. You may need to enable debug logging on all three backends to further investigate this issue (use the `--debug true` and `--log-level debug` flags with `sensu-backend start`). 

Any additional details you can share from the sensu-backend logs would be helpful.

**Comment by raihanchdy** [comment]
@calebhailey the main issue is with goland script. Attaching the error log

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf6c202]

goroutine 842469 [running]:
github.com/sensu/sensu-go/command.KillProcess(...)
        github.com/sensu/sensu-go@v0.0.0-20210114171747-6c2b13310466/command/proc_unix.go:23
github.com/sensu/sensu-go/command.(*ExecutionRequest).Execute.func2()
        github.com/sensu/sensu-go@v0.0.0-20210114171747-6c2b13310466/command/command.go:169 +0x62
created by time.goFunc
        time/sleep.go:168 +0x44

This is killing sensu-backend process without detailed info. Due to this peers etcd causing problems and the cluster is going down.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/sensu-ha-cluster-unstability/2382/3

**Comment by jvisoutsri** [comment]
running into the exact same issue as well
