### ISSUE TITLE
Concurrent websocket write panic

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4359]
sensu-backend can panic due to concurrent websocket writes. This likely happens because of a conflict between sending check requests and closing the connection.

We need to audit the agent session code and make sure that there is mutual exclusion between writing a check request and closing the connection, which writes to the websocket conn.

```panic: concurrent write to websocket connection

goroutine 1637 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0015994e0, 0xc002557201, 0xc00255723c, 0x0, 0x0, 0x7f8decab3c08, 0x30)
github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x62e
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0019bec60, 0x8, 0xc00255723c, 0x2, 0x2, 0xc001440e40, 0x1e73070)
github.com/gorilla/websocket@v1.4.2/conn.go:763 +0x249
github.com/sensu/sensu-go/transport.(*WebSocketTransport).SendCloseMessage(0xc0019bd6b0, 0x0, 0x0)
github.com/sensu/sensu-go@v0.0.0-20210625224018-d1480a492024/transport/transport.go:300 +0x86
github.com/sensu/sensu-go/backend/agentd.(*Session).stop(0xc001d74480)
github.com/sensu/sensu-go@v0.0.0-20210625224018-d1480a492024/backend/agentd/session.go:541 +0x55e
github.com/sensu/sensu-go/backend/agentd.(*Session).Start.func1(0xc001d74480)
github.com/sensu/sensu-go@v0.0.0-20210625224018-d1480a492024/backend/agentd/session.go:417 +0x5f
created by github.com/sensu/sensu-go/backend/agentd.(*Session).Start
github.com/sensu/sensu-go@v0.0.0-20210625224018-d1480a492024/backend/agentd/session.go:415 +0x1d7
```

**Comment by portertech** [comment]
In many cases, this occurs during backend crash due to an unrelated issue. We've also improved the stop procedures. Closing this one, we can re-open if we continue to see it with future releases.
